kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: argocddemo
  name: argocddemo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    k8s-app: argocddemo
